### ISSUE TITLE
Silence tracking isn't a good thing

### ISSUE THREAD

**Issue by CubixSystem** [Glavin001/atom-preview#118] opened 2016-01-04 20:43 UTC
Well, its very helpful tools, big thanks, but silence tracking isn't a good thing, now I can't trust you.
If you had time to implement tracking (for good targets, I read your description at [atom-beautify](https://github.com/Glavin001/atom-beautify/issues/47)), you should also implement ability to turn it off.
~~Maybe you implement AdSense at next release?~~
Ugh, its time to start thinking about ghostery and ublock for atom...
Anyway, thanks for your very helpful work.

**Comment by Glavin001** [comment] 2016-01-04 22:02
I definitely want to add in the ability to disable the Analytics from the Settings panel. I have been unable to commit time to this project recently because of school and work. Please submit a pull request and I would love to merge it and add this functionality for everyone to use. Thank you!

**Comment by Glavin001** [comment] 2016-01-04 22:03
I'll close this as a duplicate of #76

**Closed by Glavin001** 2016-01-04 22:03 UTC
